### ISSUE TITLE
preLaunchTask 'wmake-build' terminated with exit code-1 & launch program <folder Path> does not exsist

### ISSUE THREAD

**Issue by Prabs8815** [Rvadrabade/Debugging-OpenFOAM-with-Visual-Studio-Code#1]
Hello fellow VsCode and OF users, 

I tried installing and launching the debugging tool of vs code a couple of times but am stuck here where i get the error wmake-build not found. 

Here are the steps i did according to the description in this github 

1. Installed/ activated debug mode of openFOAM. Currently, i am using of240Debug. 
2. Changed launch.json, tasks.json andc_cpp_properties.json according to the restrictions and are as follows 

as is understand,  vs code is searching for a make file to execute but does not recognize the directory even though everything works well with terminal. 

If someone understands were i should make some changes to get it running, i would be glad for your comments. 

#Launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "OF-Debug",
           // "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "~/OpenFOAM/userName-2.4.0/SOWFA-2.4.0/src/turbineModels/turbineModelsStandard/Make",
            // "program": "${fileDirname}/${fileBasenameNoExtension}",
           // "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "wmake-build",
            //"preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}

**Comment by Rvadrabade** [comment]
Could you try to create or download the task.json file from this folder https://github.com/Rvadrabade/Debugging-OpenFOAM-with-Visual-Studio-Code/tree/master/vector/.vscode ?  If you have already build the Openfoam application with wmake from terminal then comments out preLaunchTask in launch.json above as it is not needed. Also, 'program' in launch.json above points to complete path of Openfoam solver executable not a Make file/folder. I recommend you to first understand these concepts with an example illustrated in description i.e. 'vector' in the repository. Let me know if this works.

**Comment by Prabs8815** [comment]
Hello again , 
Thanks for your comment. Here are the things i did,


 Its a good idea to get a hold of the terminology first. So i tried to run the native debugging features of vs code with gdb (launch) configuration for a random c++ program. It worked and i figured that you need to run the compiler to get a file a.out which then vs code reads to debug your program. This a.out file is created in your workspace folder and also the launch.json, task.json etc are created when you hit F5 and subsequently select the configuration you want. This is what i understood so far. 

Then, i tried to implement this on your vector case. First of all the include files vector.H and IOstream.H are not there in the folder so the compiler was complaining. Hence i run a preexisting case i had from another tutorials folder namely, cvpiso.C . The application is compiling in the terminal but the issue still persists 

in relation to this can you please give your feedback on the following

1.so, which file corresponds to  a.out in the context of  OF-Debug ?
2. program corresponds to target file location relative to workspace folder or (only) file name is enough ? 
3.  i am using as a foam extended project, so all my files are externally packaged, is this location description  still valid ?    {env:FOAM_USER_APPBIN}/${fileBasenameNoExtension}


also any general feedback is welcome

**Comment by Rvadrabade** [comment]
I encourage to open another new issue If facing same difficulties. Closings for now.
