### ISSUE TITLE
Is it possible to use openfoam in visual studio 2019?

### ISSUE THREAD

**Issue by zhang-qiang-github** [Rvadrabade/Debugging-OpenFOAM-with-Visual-Studio-Code#2]
I want to develop project with `openfoam` in visual studio 2019. Is it possible?

If it is possible, could you please give a tutorial?

**Comment by Rvadrabade** [comment]
I tried debugging Openfoam with visual studio code in Ubuntu and WSL in windows. Probably, it is possible with Visual studio 2019 as it can make connections to WSL. However, you need to find a way to invoke wmake to build Openfoam app through Visual studio. Currently, I don't have any leads on the same. 

Thanks.
